### ISSUE TITLE
Unable to press

### ISSUE THREAD

**Issue by damso93** [Fate-Grand-Automata/FGA#1026]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1577

### Describe the bug

When I want to press "start" after pressing "start device", it does not work. But the cancel  button function
![bug fga](https://user-images.githubusercontent.com/90508205/146682519-276882f9-dd63-4edf-ab10-750c89fb5009.PNG)

( i'am on bluestack ) 

### Video

https://user-images.githubusercontent.com/90508205/146682762-9e7fc9e6-129f-4081-aeba-592b775338ce.mov

### Device model

blustacks on ONEPLUS 3T

### Android version

7

### Screen size

1920X1080

### RAM

4 GB

**Comment by reconman** [comment]
If you searched for "Bluestacks" in the closed issues, you would have found the solution.

Since more and more people can't find the solution, I've added it to the Bluestacks part of the troubleshooting guide: https://github.com/Fate-Grand-Automata/FGA/wiki/Running-on-Emulators#bluestacks

It's the part about rotating your screen before you start the FGA service.

**Comment by damso93** [comment]
I had watched and read this post, I just didn't understand that it was mandatory to be on bluestacks 5
