### ISSUE TITLE
Quick double tap on skill activation (JP)

### ISSUE THREAD

**Issue by AsdAsdAsd001** [Fate-Grand-Automata/FGA#1042]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Recently in JP a new QOL update made it such that skill animation can be sped up by tapping the screen as skill animation is playing. 

I suggest adding a quick double tap to activate skills, this ensures that the skill activation is instantly sped up, thus reducing clear times.

**Comment by Kyonyuu** [comment]
there's already a double tap... actually it is there almost since the beggining... it just doesn't does the double tap for order change... this tap is useful  for in case the user made a script that use the same skill and the skill is still on cooldown or just glitch... also help in case the use likes to use "confirm skill", anyway it is still there... it's one of the reasons why most nobody asked for it...

**Comment by reconman** [comment]
I saw videos of FGA with sped up skills. Can you show videos of FGA versus you double tapping?

**Comment by AsdAsdAsd001** [comment]
https://www.youtube.com/watch?v=VUKuaBVL2P0 (FGA running the script)
https://www.youtube.com/watch?v=rJ3fkIovWQ8 (Me double-tapping skill activation)

Here are the videos you asked for. Though I admit it isn't the most accurate of tests, the double taps should be able to speed up scripts by 5 - 10s, perhaps even more. I hope you find this useful to add to the app :)
