### ISSUE TITLE
Game Detection slighty off on Wave 3 after farm for awhile

### ISSUE THREAD

**Issue by DonutCosmo** [Fate-Grand-Automata/FGA#1051]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1597

### Describe the bug

 When using double Skadi comps, usually after about 15 minutes of using FGA, the game detection for selection skills on servants miss by a little. So far this has only happened on wave 3s.

This has happened with Dantes, Lancelot, and Parvati so far. I have also tried on different maps.

This has happened in the Christmas lotto comps as well but only if I let FGA farm for 8+ hours so double Skadi seems to be the main issue.

This never happened on my Samsung Tab S7 before the ui change in FGO. 

Here are my configurations, anything not shown is default settings.

![Screenshot_20211229-094745_FGA (CI)](https://user-images.githubusercontent.com/96837780/147689732-c8e26278-b388-493c-99d4-fda73458aaf1.jpg)
![Screenshot_20211229-094751_FGA (CI)](https://user-images.githubusercontent.com/96837780/147689734-75e56287-9f0f-4602-8a43-c6383d48538e.jpg)
![Screenshot_20211229-094756_FGA (CI)](https://user-images.githubusercontent.com/96837780/147689737-8f847a42-b478-4b5b-90fb-f08b867acb9e.jpg)
![Screenshot_20211229-094820_FGA (CI)](https://user-images.githubusercontent.com/96837780/147689738-9d57bc20-6bec-48e0-bfd8-17d4b610ab8a.jpg)

### Video

https://youtu.be/nvLp_5IXQzQ

### Device model

Samsung Tab S7

### Android version

11

### Screen size

1280x800

### RAM

6gb

**Comment by reconman** [comment]
Seems like FGA thinks that Support Skadi is dead because the Star Distribution animation is still playing when it's trying to detect the number of servants.

If you look closely, there's a green rectangle on the Attack button and then 3 small rectangles on the right side of the health bars. The left 2 are green, the right one is red.

If there are only 2 servants left on the field, the skill click positions in the game shift, that's why FGA misclicks.

Increase your "Wait before Turn" setting in More Settings -> Advanced -> Fine-Tune.

**Comment by DonutCosmo** [comment]
Thank you!
