### ISSUE TITLE
Script fails after the first run

### ISSUE THREAD

**Issue by saiyan11** [Fate-Grand-Automata/FGA#1057]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1597

### Describe the bug

I program the script to run the same quest 3 times in a row.
The first time it goes perfectly, but the next ones it skips NPs, doesn't click on skills or selects skills or NPs in a wave in which they shouldn't be activated.

For example: in the second run the script selects all NPs whereas it should only select Koyanskaya's. Here my configuration:
<img height="800px" src="https://user-images.githubusercontent.com/97035584/147937948-2c4958a4-0f16-4f65-a05b-1d739c9313f6.jpg" />
<img height="800px" src="https://user-images.githubusercontent.com/97035584/147937951-7bd349b2-a2c4-4ab4-a57d-6d6f152099f1.jpg" />
<img height="800px" src="https://user-images.githubusercontent.com/97035584/147937952-6e3701d2-11bf-4ba5-8441-f42c9a59a7db.jpg" />
<img height="800px" src="https://user-images.githubusercontent.com/97035584/147937953-77593ed7-8101-4447-b864-7c099342e134.jpg" />
<img height="800px" src="https://user-images.githubusercontent.com/97035584/147937954-eb7f6b88-209b-4e9e-bbaa-6c0ae8e8a993.jpg" />

### Video

https://youtu.be/yA5RzjvaJFI

### Device model

Xiaomi Redmi Note 7

### Android version

10

### Screen size

1080x2340

### RAM

6 GB

**Comment by reconman** [comment]
I think it's because the Retry on Death feature doesn't work correctly.

**Comment by reconman** [comment]
After looking closely at your video, I see a few things going wrong:

1. Servant Details for your own Servants aren't opened correctly. That's probably because of timing issues.
2. Skills are executed normally, but NP Spam is broken in the 2nd run.

For the first problem, increase your "Wait before turn" delay in the Fine-Tune settings. The crit star animation playing when Morgan's CE effect is activated is the problem why she isn't detected. I would propose a setting of 2000-2500 ms.

I currently can't think of a way to handle that better. That will maybe also fix the 2nd problem.

**Comment by saiyan11** [comment]
I downloaded the last build (1599) and now it works fine. Thanks for your hard work.

**Comment by reconman** [comment]
I didn't fix anything, you still need to change what I told you to.
