### ISSUE TITLE
Failed to determine Card type

### ISSUE THREAD

**Issue by metapone** [Fate-Grand-Automata/FGA#1165]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1669

### Describe the bug

After a few runs FGA will report "Failed to determine Card type" for certain servants. I'm guessing this is due to the Servant Ascension Randomization feature, because I could see FGA trying to recognize certain servants twice and then giving up.

### Video

https://youtu.be/bmloHkQkPHo

### Device model

Xiaomi Redmi Note 5

### Android version

11

### Screen size

1080 x 2160

### RAM

4GB

**Comment by potchy** [comment]
I have a friend with the same problem, but on Bluestacks.
I think that's because your phone starts lagging a couple of minutes.
The screen recording function Automata relies on (Media Projection) is pretty resource intensive.
I think you could try tweaking the setting in More options -> Advanced -> Fine-tune -> Wait (the 5th tab) -> Wait before Cards. 3000ms~5000ms should do it.

If that's an option for you, you could also try root mode, which is leagues faster than Media Projection.
