### ISSUE TITLE
iOS Version of FGA?

### ISSUE THREAD

**Issue by Kuon0** [Fate-Grand-Automata/FGA#1221]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Sorry if this is a really dumb question. I was wondering if it was possible for an .ipa version of FGA to be made?

**Comment by reconman** [comment]
Will never happen because:

- The app is written with some Android-only frameworks, the app would need to be completely rewritten
- Mathew and me don't have iOS devices, so we can't changes
- According to my knowledge, you need to Jailbreak your device to install .ipa files. We had some negative experience with Play Store Reviews because people just kept writing about problems described in the Troubleshooting Guide. The same would happen with the iOS store, assuming Apple even allows the app.
