### ISSUE TITLE
Why can't we pick multiple apple options at the same time now?

### ISSUE THREAD

**Issue by ClownHassan** [Fate-Grand-Automata/FGA#1305]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Question is the title but pretty much, why was the feature to use Bronze,Silver, and Gold Apples either removed or is disabled?

**Comment by reconman** [comment]
JP introduced another apple type, which requires scrolling.

The old code only worked because no scrolling was required. Now scrolling would close the confirmation dialog, so I had to disable selecting multiple apples.

I would need to check for the presence of the OK button instead of blindly clicking on its location. I'm still missing the image for a few servers.
