### ISSUE TITLE
Samsung S22 Screen Detection is incorrect

### ISSUE THREAD

**Issue by Cwang5614** [Fate-Grand-Automata/FGA#1309]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1781

### Describe the bug

Recently switched from my Samsung S10 over to the S22 after using FGA for years. Can't seem to get it to work on the new phone. Have FGO on full screen, with ignore Notch calculation turn on, with default area mode. But based on Debug mode, everything seems off. Am I missing something by being stupid? 

### Video

https://user-images.githubusercontent.com/78830477/186038681-d1eb2baa-7ae8-4ed6-b6b9-8421a7f9bdb5.mp4

### Device model

Samsung S22

### Android version

12

### Screen size

1080x2340

### RAM

8

**Comment by azh97** [comment]
Maybe need to toggle skill confirmation to on for FGA?

**Comment by chilipadi** [comment]
@Cwang5614 not sure what you mean by "everything is off".
However, after that latest NA update, my existing Battle Configs went totally bonkers - skills were activated when they shouldn't have. My fix was to rewrite brand new battle configs. (Thank goodness it worked, since shishoufest...)
BTW, am using an S22 Ultra (FGO full screen, ignore notch calc, default area).
