### ISSUE TITLE
Supports and apples are not selected

### ISSUE THREAD

**Issue by ShadowDragon1329** [Fate-Grand-Automata/FGA#1331]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1801

### Describe the bug

It does not choose supports and apples and skills are not selected properly.

### Video

https://www.youtube.com/watch?v=BrYR-QTHToI[https://www.youtube.com/watch?v=BrYR-QTHToI](url)

### Device model

one plus 8 pro

### Android version

12

### Screen size

1280x720

### RAM

8

**Comment by reconman** [comment]
Troubleshooting Guide, section Game Area

> On some devices like OnePlus, the black bars on the sides are caused by gesture navigation. See CASE 2 for the solution.

If you post a screenshot, I could help you with measurements.

**Comment by ShadowDragon1329** [comment]
![Screenshot_2022-08-26-21-16-51-84_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/102644403/186944073-6441f6b7-2762-42f4-bdd1-cffb42ea8db6.jpg)
![Screenshot_2022-08-26-21-17-12-24_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/102644403/186944105-901c1c42-7cff-4145-b25b-10c77e31be0f.jpg)
This are the screenshots that I have ,if these don't suffice then please inform me.

**Comment by reconman** [comment]
Try Custom Game Area with left=101.

Yesterday I switched from Gesture Navigation back to 3-button navigation on my OnePlus 9 and noticed that since some FGO update, the notch is shown on the left even in 3-button navigation. That's what you're also experiencing right now.

If you enable Gesture Navigation, the black bar on the left gets bigger and there's also another bar to the right because FGO thinks that the 3-button navigation bar is showing up.

If 3-button navigation is enabled, I can measure the navigation bar height just fine, but once I switch to Gesture Navigation, the navigation bar height is set to a (wrong) default value.

I probably invert the "Ignore Notch" at some point, so it becomes something like "Treat Notch as unusable". Not sure what's the best name for it. With that option, you don't need the Custom Game Area anymore.

**Comment by ShadowDragon1329** [comment]
Thank you man it works now , now I can finally get around to using those apples
