### ISSUE TITLE
LD Player 9 every 20mins card type fails to determine 

### ISSUE THREAD

**Issue by CapYuno** [Fate-Grand-Automata/FGA#1341]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1805

### Describe the bug

Im on LD Player 9 S10 device set as my model. 

Everytime the run comes down to the final ap it can use before it uses an apple. It'll screw up the last run by clicking on castoria (1st servant) info screen. Happens when its down to the last run before ap finishes and on the 3rd wave

https://user-images.githubusercontent.com/86341130/187041454-e80c48db-a7ed-4869-8874-fe38790d6265.mp4

the video is a 20 min run cut to the part where it dies. Happens like this everytime

### Video

https://user-images.githubusercontent.com/86341130/187041703-11d2ab91-2940-421e-8716-19c2d5a7bd95.mp4

### Device model

LD PLAYER 9

### Android version

9

### Screen size

1600x900

### RAM

8gb

**Comment by reconman** [comment]
Probably fixed in build 1818.

When it clicks on the Master skill, it waits for the Attack button to vanish and then reappear. Even though the Attack button is getting more and more transparent, the "is present" check hits, so FGA thinks that FGO is ready for the next step, which is clicking the Attack button. But at that point, the Attack button hasn't reappeared yet.

I've added a fixed wait time of 0.5 seconds after each skill cast, which may slow down some devices, but will probably also prevent a lot of errors like on your emulator.
