### ISSUE TITLE
How to get coordinates on android studio

### ISSUE THREAD

**Issue by TheRealPlagiariser** [Fate-Grand-Automata/FGA#1355]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I may work on this later, could you let me know how the locations/ regions coordinates are being obtained? I checked with inbuilt pointer coordinates (bluestacks and developer mode) none seem to reflect the examples in the script.

**Comment by reconman** [comment]
Let's take this screenshot from my phone as example:

![grafik](https://user-images.githubusercontent.com/12360257/187491666-e32855c6-e6f5-4b1d-8073-4831d8e7e925.png)

The resolution is 2400x1080, but it has black bars on the sides.

1. Remove the black bars, that's 168 pixels on the left, 68 pixels on the right (configured via Custom Game Area). So the image is now 2164x1080.
2. Scale the image to 1440p. Now the image is 2885x1440p. (rounded)
3. x=0,y=0 is top left. x=2885,y=1440 is bottom right. x=1443,y=720 is center.

Next, you'll have to determine which gravity UI elements have. Are they centered? Do they stick to the left or to the right?

All windows appearing in the middle of the screen (e.g. confirmation screens, AP refill, ...) are centered, so you'll have to use `Location.xFromCenter()` or `Region.xFromCenter()` to automatically add half of the 1440p scaled screen width (minus the black bars) to the X coordinate.

`Location(0, 0).xFromCenter().yFromBottom()` would give me x=1443,y=1440.

`Region(x=-100, y=300, width=200, height=200).xFromCenter()` creates a Rectangle which is centered on the screen because it starts 100 pixels to the left of the center and is 200 pixels wide, so it also goes 100 pixels to the right.

**Comment by TheRealPlagiariser** [comment]
> Let's take this screenshot from my phone as example:
> 
> ![grafik](https://user-images.githubusercontent.com/12360257/187491666-e32855c6-e6f5-4b1d-8073-4831d8e7e925.png)
> 
> The resolution is 2400x1080, but it has black bars on the sides.
> 
> 1. Remove the black bars, that's 168 pixels on the left, 68 pixels on the right (configured via Custom Game Area). So the image is now 2164x1080.
> 2. Scale the image to 1440p. Now the image is 2885x1440p. (rounded)
> 3. x=0,y=0 is top left. x=2885,y=1440 is bottom right. x=1443,y=720 is center.
> 
> Next, you'll have to determine which gravity UI elements have. Are they centered? Do they stick to the left or to the right?
> 
> All windows appearing in the middle of the screen (e.g. confirmation screens, AP refill, ...) are centered, so you'll have to use `Location.xFromCenter()` or `Region.xFromCenter()` to automatically add half of the 1440p scaled screen width (minus the black bars) to the X coordinate.
> 
> `Location(0, 0).xFromCenter().yFromBottom()` would give me x=1443,y=1440.
> 
> `Region(x=-100, y=300, width=200, height=200).xFromCenter()` creates a Rectangle which is centered on the screen because it starts 100 pixels to the left of the center and is 200 pixels wide, so it also goes 100 pixels to the right.

Thanks for the explanation. Although this still feels a bit like trial and error to me, I can manage though with that info.
