### ISSUE TITLE
How about adding a feature to choose which phone you're playing it on?

### ISSUE THREAD

**Issue by KimmynoHeaven** [Fate-Grand-Automata/FGA#1410]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

So some phones right now has issues on running because of the screen size, so why not add the feature to select which phone you're using? For example I'm using Z flip 4 right now, and it doesnt work since indicator boxes doesnt fit on buttons. Maybe it might help people who has same issue as me?

**Comment by Awakens** [comment]
That might bloat the app  
Have you tried going to
More Options -> Advanced -> Game Area Mode
to adjust the area? With Debug turned on as well

**Comment by reconman** [comment]
That would require all users to submit their custom game area values.

And then there can be different black bars for different OS versions on the same device.

Even if users want to submit their custom game area values, that would require running a server somewhere to keep track of those values.

Additionally, FGA currently has no Internet permission because some users got paranoid about us stealing accounts.

This feature is too difficult to implement and depends on the community, so I will reject it.
