### ISSUE TITLE
Support List Update button moved

### ISSUE THREAD

**Issue by reconman** [Fate-Grand-Automata/FGA#1418]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1855

### Describe the bug

The Support List Update button moved with the latest app update. Now it doesn't update the list and selects a random Support instead.

### Video

![](https://user-images.githubusercontent.com/12360257/198254118-1d98907d-e244-4c3b-8e6b-eac027acc46f.png)

### Device model

OnePlus 9

### Android version

12

**Comment by xiedwards22** [comment]
omfg same problem please help

**Comment by latiavolt** [comment]
Hello @reconman -- this is still an issue for me even with the latest canary build (build 1951). I am using an android device with no notch area, but it seems to hit "Skill Display" instead of "Update List" whenever it cannot find a suitable servant. All of the other functions work for the most part, with the exception of occasionally things not working with Space Ishtar's 2nd skill. I can try attaching a video with the behavior, but was wondering if there were any quick fixes. Thanks!
