### ISSUE TITLE
Fuzzy Taps

### ISSUE THREAD

**Issue by NozomeAkimoto** [Fate-Grand-Automata/FGA#1441]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Greetings. The latest update on the JP app has introduced a new change to the TOS that includes data collection for a company called Repro, which seems to be related to customer behavior analysis. For context, the update on the official site mentioning this is here:

[https://news.fate-go.jp/2022/1109rkyc/](url)

In the case that this might result on FGA being easily detectable through taps being consistently made on the same spot, would it be necessary to consider implementing measures to slightly randomize tap positions/timing to obfuscate the use of automation?

**Comment by vybze** [comment]
Saw this on the rayshift discord server 
![Screenshot_2022-11-10-18-02-32-976_com discord](https://user-images.githubusercontent.com/32293918/201241135-21a317b7-764d-44ab-b56f-4a65543236e5.jpg)

**Comment by reconman** [comment]
Fuzzy taps doesn't always work, since some FGA click locations are pretty precise, so it would have to be case by case.

And currently most people think that the tapping detection will not be used against bots, especially with arguments like these:
![image](https://user-images.githubusercontent.com/12360257/201740195-e05ac1ab-e7ca-4acc-9243-ee1f9ac52312.png)
