### ISSUE TITLE
Failing to Determine Card Type

### ISSUE THREAD

**Issue by GourmetNewell** [Fate-Grand-Automata/FGA#1450]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1888

### Describe the bug

Cards randomly seem to be unrecognized. The beginning of the battle when FGA is activated starts fine (selects the servants to capture their icon and then activates the commanded skills) but when card selection begins, it seems to be a dice toss whether the cards get recognized afterwards. Its rare for it to happen on turn 1 but usually this happens on turn 2 or 3 which is when I have plugsuit activated to swap a servant in/out. 

![Screenshot_20221118-144027](https://user-images.githubusercontent.com/55465083/202800157-e474da48-a983-46e9-905b-80b4b136fb9a.png)

### Video

![Screenshot_20221116-215959](https://user-images.githubusercontent.com/55465083/202801911-f08f34fd-838a-41ac-ab14-e48c76cf04c6.png)
Dont have a video due to the Android version not playing well with screen recordingd and FGA but this should be sufficient. Debug mode showed nothing out of the ordinary with its scan of the cards.

### Device model

Google Pixel 6

### Android version

13

### RAM

8 gb

**Comment by reconman** [comment]
> Dont have a video due to the Android version not playing well with screen recordingd and FGA

That's not true anymore, 1888 is fine with Andoid's recorder. Please try again.

Without a video, I can't find the error source.

**Comment by GourmetNewell** [comment]
> > Dont have a video due to the Android version not playing well with screen recordingd and FGA
> 
> That's not true anymore, 1888 is fine with Andoid's recorder. Please try again.
> 
> Without a video, I can't find the error source.

![Screenshot_20221118-193714](https://user-images.githubusercontent.com/55465083/202828312-3cba26f4-605c-451d-8b71-80464b4433e5.png)

Heres what I get when I try making a recording.

**Comment by GourmetNewell** [comment]
I switched back to version 1856 and this is no longer an issue. So whatever changed between that version and the latest version is the source.

**Comment by reconman** [comment]
The only differences between 1856 and the current version are:

1. Removed recording function
2. Restart MediaProjection if it gets broken by the system recorder
3. Changed brave chain code (should still act the same because the Brave Chain code acts after detecting face cards)
4. Updated the Android version in the preferences module
5. Always speed up skill animations

I've changed 2. so it restarts differently. I've also reverted 3. just to be sure.

I've also improved the error message so it says which part of the detection failed: Buster/Arts/Quick or Servant detection.

Can you try if recording works with https://github.com/Fate-Grand-Automata/FGA/suites/9429925094/artifacts/445679456 and if the error still happens?

**Comment by GourmetNewell** [comment]
> The only differences between 1856 and the current version are:
> 
> 1. Removed recording function
> 2. Restart MediaProjection if it gets broken by the system recorder
> 3. Changed brave chain code (should still act the same because the Brave Chain code acts after detecting face cards)
> 4. Updated the Android version in the preferences module
> 5. Always speed up skill animations
> 
> I've changed 2. so it restarts differently. I've also reverted 3. just to be sure.
> 
> I've also improved the error message so it says which part of the detection failed: Buster/Arts/Quick or Servant detection.
> 
> Can you try if recording works with https://github.com/Fate-Grand-Automata/FGA/suites/9429925094/artifacts/445679456 and if the error still happens?

I just tried it. Screen recording is still broken but at least it does something different now. FGA no longer crashes and stops but the screen recording just stops when FGA is activated, even though Android is telling me the recording is still rolling while the FGA battle config is running. Card types were still failing to be detected and the refill screen caused FGA to stall indefinitely. 

Note that while screen recording didn't work for me on version 1856, everything else did. That includes face card identification and AP refills. 

I'd upload the video that was recorded if I could but since I cant, I can describe it: I turned on screen recording, then pressed the play button for FGA and selected my battle config, pressed OK, and thats where the video recording was ended (again, recording was still showing as going on when I ended it after the battle, but it only recorded up to the point when I activated FGA)

**Comment by reconman** [comment]
@GourmetNewell @balonbao247 @Mizu0025 @storiixp @NepPure @Abyss63, @Werror23 @lambatman103 @Uathach
Please test https://github.com/Fate-Grand-Automata/FGA/suites/9632689899/artifacts/460256600

I can't say if the bug is fixed or not, I don't experience your problems. The only problem I had on my phone was FGA crashing every now and then when I didn't use it.

**Comment by SouLIke86** [comment]
> @GourmetNewell @balonbao247 @Mizu0025 @storiixp @NepPure @Abyss63, @Werror23 @Iambatman103 @Uathach Please test https://github.com/Fate-Grand-Automata/FGA/suites/9632689899/artifacts/460256600
> 
> I can't say if the bug is fixed or not, I don't experience your problems. The only problem I had on my phone was FGA crashing every now and then when I didn't use it.

I have all of the issues described in this thread including FGA chosing wrong skill targets but for build 1904. Should I report this as a new bug because it's different build? Also tried installing that APK but it tells me it's invalid.

**Comment by storiixp** [comment]
> @GourmetNewell @balonbao247 @Mizu0025 @storiixp @NepPure @Abyss63, @Werror23 @Iambatman103 @Uathach Please test https://github.com/Fate-Grand-Automata/FGA/suites/9632689899/artifacts/460256600
> 
> I can't say if the bug is fixed or not, I don't experience your problems. The only problem I had on my phone was FGA crashing every now and then when I didn't use it.

I installed Build 1904 and it's working fine now thank you!

**Comment by Uathach** [comment]
> @GourmetNewell @balonbao247 @Mizu0025 @storiixp @NepPure @Abyss63, @Werror23 @Iambatman103 @Uathach Please test https://github.com/Fate-Grand-Automata/FGA/suites/9632689899/artifacts/460256600
> 
> I can't say if the bug is fixed or not, I don't experience your problems. The only problem I had on my phone was FGA crashing every now and then when I didn't use it.

FGA still skips skills in 1904

**Comment by SouLIke86** [comment]
> Please try build 1906 from https://github.com/Fate-Grand-Automata/FGA/releases.

1906 fixed it completely for me thank you. Although through testing I did find that using the android recording feature causes fga to fail in determining card types. It's not an issue for me but I just thought you should know. Would you like me to make a proper bug report on it? @reconman

**Comment by Mizu0025** [comment]
> @GourmetNewell @balonbao247 @Mizu0025 @storiixp @NepPure @Abyss63, @Werror23 @Iambatman103 @Uathach Please test https://github.com/Fate-Grand-Automata/FGA/suites/9632689899/artifacts/460256600
> 
> I can't say if the bug is fixed or not, I don't experience your problems. The only problem I had on my phone was FGA crashing every now and then when I didn't use it.

All fixed on build #1908, it seems. I didn't get the error after 3 runs of a battle script.

**Comment by GourmetNewell** [comment]
Hey reconman just want to let you know that the issue no longer exists on the latest version for me. Whatever you did worked. Pat yourself on the back for me.

**Comment by EveSkyHiker** [comment]
Platform: NoxPlayer 7.0.6.1

Device model:
Samsung Galaxy Note 10+

Android version: 9

Screen size: 1280x720

RAM: 6144MB
CPU: 6 core
Enhanced compatibility mode (OpenGL+) activated

FGA:
Advanced >
Debug mode: No
Use root for Screenshots: Yes

Fine tune >

Clicks >
Wait after clicking: 600ms
Click duration: 100ms
Multi-click Interval: 20ms

Swipes >
Wait after swiping: 1400ms
Swipe duration: 600ms

Wait >
Skill Delay: 1000ms
Wait before turn: 2000ms
Wait before cards: 5000ms

I've had this error for a while now, so I had put this amount of MS to make sure it would fix, but unfortunately I'm having to opt for a macro, which works around 20-30 mins and close the character status window, to move on after a while because of this error.

I was also using auto spam mode, only for turn 3, and also using some skills to be used manually in that same turn 3, and the ult together. I don't know if this interferes in anything, but I would like to know, and also to inform, about it. I turned off auto spam mode, to see if the error would be corrected, but unfortunately it also persists.

I would like to know, mostly, if there is a way to correct this error "Failed to determine Card: [1, 2, 3, 4, 5] Card type could not be detected (Buster, Quick, Arts)", because the application simply crashes and cannot move forward in any way
![imagem 1](https://github.com/user-attachments/assets/fbd67ea4-3fa9-4346-bd33-f125570ab08a)
![imagem 2](https://github.com/user-attachments/assets/f7e81127-0df3-4740-9d52-27ec81c4bb73)
![imagem 3](https://github.com/user-attachments/assets/b1f65986-ce03-4d4f-a9be-4a57ae363143)
