### ISSUE TITLE
A suggestion for higher playing efficiency

### ISSUE THREAD

**Issue by EarthPretender** [Fate-Grand-Automata/FGA#1508]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Keep clicking in a useless corner, so that it can skip many processes. (If I am not wrong, it once did like that in an older version of FGA?)

**Comment by papereater42** [comment]
Also, have it speed up enemy death animations

**Comment by reconman** [comment]
Skip enemy death is an FGO feature. Speed up skills is built into FGA.

Are you maybe experiencing #1494? Is your screen ultrawide?

I'll need a video if not.

**Comment by EarthPretender** [comment]
> 

Emmmm...I mean, for example, keep clicking to skip the starting animation(as in the Koyanskaya event).

**Comment by umomgeay** [comment]
> Also, have it speed up enemy death animations

I would also like to see fga keep clicking on enemy death. to speed up farming.

**Comment by reconman** [comment]
Like I said, enemy death is part of FGO:
![Screenshot_2022-12-25-22-58-30-04_f98d04a6a5569a2ca2cd39796e1f730e](https://user-images.githubusercontent.com/12360257/209482974-9f58177e-795d-470b-b225-74728dd2ff45.jpg)

Start of battle skips seem hard to implement since I can't detect a starting battle easily since all the buttons are still missing.
