### ISSUE TITLE
Usage of card priority and servant priority

### ISSUE THREAD

**Issue by sasakiyori** [Fate-Grand-Automata/FGA#1514]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ ] My question isn't answered in any other issues (even the closed ones)

### Your question

I want to know the usage of card priority and servant priority like:

1. WB, RB means what?  weak buster?
2. If I always want a buster chain, what should I do
3. If I want to choose the same servant's cards as more as better, what should I do

**Comment by reconman** [comment]
W = Weak
R = Resistant

FGO uses both of those words directly, so FGA does the same.

If you always want to use Buster Chains, change the card priority to WB, B, RB, WA, WQ, RA, RQ. That way, buster cards have priority, even if the enemy resists them.

For Servant Priority, enable it in the Card Priority settings of a Battle Config and then rearrange the 1-6 cards at the bottom. Each number corresponds to the position of the Servant in your team. So 1 is the left one, 2 is the middle one and 4-6 are for the backrow.

**Comment by sasakiyori** [comment]
I get it. Thanks for your detailed answer!

**Comment by mahnoorfirdous** [comment]
For me it doesn't seem to work. I've toggled and shut the service down and the app down over and over. I wanted servant 2 to have priority no matter what because they're the one with crit buffs but it ignores me and just goes for card priority every time. It makes my support hit and that drags things to an extra 2 turns
