### ISSUE TITLE
how would I go with making similar stuff for other apps?

### ISSUE THREAD

**Issue by ozne1** [Fate-Grand-Automata/FGA#1637]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

title. As someone with no experience in making android stuff, how could I make something similar to this but for other apps?

**Comment by reconman** [comment]
To build another Android app like FGA, you'll have to learn:

- Java or Kotlin
- Groovy build system
- Android Fragments or Jetpack Compose for UI
- Android Accessibility and MediaProjection
- Image detection library OpenCV

Don't start if you don't know Java or Kotlin.

If you're experienced in those languages, it will still take you 1 month to build the UI that does nothing.

After that, you'll have to learn about taking screenshots and searching for images in them, which will probably take another month and is pretty tricky.

It's easier if you start with an Ankulua script instead of building your own app, that's how FGA started.

https://github.com/29988122/Fate-Grand-Order_Lua

You'll be time-limited, but it's much quicker to get something that works.
