### ISSUE TITLE
Add more Japanese translation

### ISSUE THREAD

**Issue by endo613** [Fate-Grand-Automata/FGA#1644]
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

We are currently preparing a Japanese translation of the file. However, I do not understand the behavior of the application and some parts are not translated. We would appreciate it if you could explain the functionality to us so that we can translate it correctly. The functions I do not understand are as follows If you could please explain when they are displayed and how they behave or do not behave when set, I would be able to understand them better.

1,
`<string name="skill_maker_atk_cards_before_np">Cards before NP</string>`

2,
`<string name="p_spam_summary">Danger mode requires Auto-targeting</string>`
`<string name="p_auto_choose_target">Auto choose target</string>`

3,
`<string name="p_enable_withdraw">Enable Withdraw</string>`

4,
`<string name="p_stop_on_ce_get_summary">First-time quest completion rewards and Bond CEs (Experimental)</string>`

5,
`<string name="p_rearrange_cards">Rearrange Cards</string>`

7,
`<string name="p_root_screenshot">Use Root for Screenshots</string>`
`<string name="p_root_screenshot_summary">Useful on Nox (Android 7). Toggle service after changing this.</string>`

8,
`<string name="p_boost_item_disabled">Disabled</string>`
`<string name="p_boost_item_skip">Skip</string>`

9,
`<string name="spam">Spam mode</string>`
`<string name="spam_target">Target</string>`
`<string name="spam_np">NP:</string>`
`<string name="p_spam_none">None</string>`
`<string name="p_spam_spam">Spam</string>`
`<string name="p_spam_danger">Danger</string>`

10,
`<string name="failed_to_determine_card">Failed to determine Card: %s</string>`

11,
`<string name="unknown_servant_card">Card belongs to an unknown Servant</string>`
`<string name="support_list_updated_in">Support list will be updated in %s</string>`
`<string name="times_withdrew">Withdrew %d times</string>`

12,
`<string name="picked_exp_stacks">Picked %d EXP stacks, resulting in a total amount of %d Gold embers</string>`

13,
`<string name="p_shuffle_cards">Shuffle cards</string>`
`<string name="p_shuffle_cards_wave">Wave</string>`
`<string name="p_shuffle_cards_when">When</string>`
`<string name="p_shuffle_cards_when_none">None</string>`
`<string name="p_shuffle_cards_when_no_effective">No effective cards</string>`
`<string name="p_shuffle_cards_when_no_np_matching">No cards matching NP</string>`

14,
`<string name="p_game_area_mode">Game Area Mode</string>`
`<string name="p_game_area_default">Default</string>`
`<string name="p_game_area_duo">Surface Duo</string>`
`<string name="p_game_area_custom">Custom</string>`
`<string name="p_game_area_custom_left">Left</string>`
`<string name="p_game_area_custom_top">Top</string>`
`<string name="p_game_area_custom_right">Right</string>`
`<string name="p_game_area_custom_bottom">Bottom</string>`

**Comment by reconman** [comment]
1. Use 1 or 2 face cards before triggering the Noble Phantasm
2. Auto choose target means to select enemies with DANGER or SERVANT. SERVANT has higher priority than DANGER. After enabling "Auto choose target", users can enable the Spam mode "Danger" so FGA triggers skills or NPs when it sees those enemies
3. When you lose a battle, you are asked if you want to use 1 Saint Quartz, 3 Command Spells or Withdraw. This option clicks on Withdraw and then starts the quest again.
4. "Stop on CE GET" reacts to getting CEs as quest reward or via reaching Bond 10. It will stop farming once it encounters the new CE screen
5. "Rearrange Cards" puts the cards in the order where the card with the highest priority is used last. For example, if you have set the card priorities to Buster > Arts > Quick, then the normal algorithm would use BAQ. "Rearrange cards" would use QAB, I think.

You left out "6,"

7. "Use Root for Screenshots" refers to [rooting your phone](https://ja.wikipedia.org/wiki/Root%E5%8C%96_\(Android_OS\)). If you have, FGA can use special tools to take screenshots instead of using MediaProjection. On some emulators like Nox this is required so FGA can work.
7. This refers to a functionality for events where you have to pick 1 of 3 items to increase event points. For example, this event had "クイックオイル", "アーツニトロ " and "バスターガソリン ": https://fategrandorder.fandom.com/wiki/Dead_Heat_Summer_Race!
8. These refer to a "Spam mode" where FGA tries to use skills and NPs whenever it can or when a Danger/Servant enemy appears (see 2.)
9. Error message when the face card cannot be associated with a Servant or the type (Buster, Arts, Quick) cannot be read
10. For "unknown_servant_card" see 9. "support_list_updated_in" informs the user that no matching support was found and that the Support list will be updated in a few seconds. The "Update" button has a 10 second cooldown, that's why FGA has to wait. "times_withdrew" is related to 3.
11. Related to the Gift Box mode where it collects 3* and 4* EXP cards for you. EXP stack = 1 entry in the gift box. "ember" is an EXP card.
12. Functionality for shuffling cards with 魔術協会制服 in certain conditions
13. On some devices, black bars are present. FGA offers functionality for ignoring these black bars by telling the app how big the black bars are. See https://github.com/Fate-Grand-Automata/FGA/issues/1347 for a thread where a bot measures the black bar and tells users what to configure. "Surface Duo" is a special mode for https://ja.wikipedia.org/wiki/Microsoft_Surface#Surface_Duo/Neo_%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA which only works for that single device

**Comment by endo613** [comment]
Thanks for the reply. So far I have been able to do the following, but I have some additional questions.
1, this one seems fine.
2, I don't understand enough about spam mode.
3, Is there a continue function here with a decree or holy stones?
4, In More Options>Battle, there are two items "Stop on CE GET" and "Stop on first-clear rewards", but the explanation for "Stop on CE GET" is "First-time quest completion rewards and Bond CEs (Experimental)" is listed as the explanation for "Stop on CE GET". Is it correct to assume that "Stop on CE GET" only works when there is a CE as a first-time quest completion reward?
7,Is there a setting on Nox for "Toggle service" in "Toggle service after changing this.
8, I think the boost item selection screen has three choices: "Cancel", "Start quest without using item", and "Confirm boost item use (on or off)", which is assigned to "Disabled" and "Skip"?
9, Is spam mode a FGA-specific term?
10, Do you have a screenshot of this one? I would like to provide a translation that matches the screen shown.
11, Do you have a screenshot of this one? I would like to provide a translation that matches the screen shown.
12, Do you have a screenshot of this one? I would like to provide a translation that matches the screen shown.
13, When are the following two activated? Is it in conjunction with the card priority setting? Also, when is the setting that is executed when there is no NP card(?)? What is the effect of the setting when there is no NP card?
<string name="p_shuffle_cards_when_no_effective">No effective cards</string
<string name="p_shuffle_cards_when_no_np_matching">No cards matching NP</string
14, this one looks fine.
[localized_jp.txt](https://github.com/Fate-Grand-Automata/FGA/files/12251102/localized_jp.txt)

**Comment by reconman** [comment]
### 2 and 9
To spam = repeat something many times or send something to many recipients
In this case, it's when users want to use Noble Phantasms or Skills as often as possible.

Example: I want to use the same battle configuration for 2-turn and 3-turn Rank-Up quests. I set Edmond Dantes' Attack Up and Scathach-Skadi's Defense Down to DANGER mode so they are used in wave 2/2.

### 3
No, continue is not supported, FGA will stop if Withdraw is disabled.

### 4
"Stop on first clear reward" is for clearing Free Quests 3x until you get the Saint Quartz (you called it holy stone) or Apples
It's pretty rare to get CEs as quest rewards, so 99 % of the cases it stops on Bond CEs.

### 7
It refers to clicking on the red "Stop Service" button in the bottom right of the app and then clicking on "Start Service" again.

### 8
Disabled = the dialogue does not appear (normal farming and events)
Skip = Start quest without using an item

### 10 and part of 11
See end of https://streamable.com/nur5rg
That is the old error message which appeared both for unknown faces and for unknown card types (Buster, Arts, Quick)

### 11
Which of the 3 are you talking about? They're all related to different modes/screens

### 12
Open the present box and then press the Play button. You'll see the text.

### 13
No effective cards = When there are no face cards with "Weak" on them. For example, if the enemy is Archer and you only have Caster cards.
No cards matching NP = It would shuffle when you have a command to use the 1st Servant's Noble Phantasm but there are no face cards for that Servant. If you trigger 2 Noble Phantasms in the same turn (Artoria Caster Noble Phantasm + Muramasa Damage Noble Phantasm), it will only shuffle if there are 5 cards for the 3rd Servant.

**Comment by endo613** [comment]
Thank you for your persistent follow-up.
Thanks to you I was able to translate all of the files I had saved. I will send them as a pull request for your review.

...Sorry, I'm not quite sure how to use Github and I don't think I'm doing it right.

I am also attaching the file I created below, which I hope you can use.

[localized_jp.txt](https://github.com/Fate-Grand-Automata/FGA/files/12268972/localized_jp.txt)

**Comment by reconman** [comment]
@endo613 I'm still waiting for your corrections.

**Comment by reconman** [comment]
You already submitted a Pull Request at https://github.com/Fate-Grand-Automata/FGA/pull/1653, now I'm waiting for you to add a 2nd commit.

The easiest way is to:
1. Go to https://github.dev/endo613/JP-translations/tree/JP-translations
2. Open the Japanese localized.xml
3. Make the corrections I requested in the Pull Request and press Ctrl+S to save the file
4. Switch to the "Git" tab on the left, enter a commit message and press Commit & Push
![image](https://github.com/Fate-Grand-Automata/FGA/assets/12360257/63901366-31fd-4679-996e-d0d7050e33d3)

**Comment by reconman** [comment]
Alternatively, you can join https://poeditor.com/join/project/67PXOyBGI0 and add your translations there.

**Comment by endo613** [comment]
Thank you. I have replied and edited.

**Comment by reconman** [comment]
> Thank you for your explanation. I have made a 2nd commit and opened a poEditor account, so I will edit any future sutras from here, but is there any inconvenience?

I don't think there are any drawbacks, but I'll have to check how well it works first.
