### ISSUE TITLE
Service doesn't start after stopping

### ISSUE THREAD

**Issue by Squork** [Fate-Grand-Automata/FGA#1878]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2826

### Describe the bug

Broken in latest Google Play update (2816 or smth about), still broken in latest github release (2826). Works when rolled back to 2740.

What was: after every press on "Start service" button, Android asked do I really wants to start the screen record.
What now: when I start service first time, Android asks this. When I stop service and start it again, Android does not ask this. Play button appears correctly but does nothing. Turning accessibility settings off and back on does not help.

(Maybe you may just add a switch for service start method: old/new?) 

### Video

(is a video really needed here?) 

### Device model

Oneplus 9R (Oxygen OS - Android 14.0) 

### Android version

13

### Screen size

1080x2400

### RAM

12gb

**Comment by mgscab** [comment]
same issue. Galaxy S24 ultra. Requires complete phone restart for it to continue functioning, and only once, then requires a phone restart once again.

**Comment by mgscab** [comment]
Trying to record the issue myself
apparently the update makes it so that trying to record the issue is more difficult than expected. If I have the built in screen recorder running and press the play icon, the play icon will disappear. If I have the screen recorder running and select the "start now" button, the screen recorder stops recording video but continues to record audio. There have been other issues as well, where for some reason I have to occasionally reset the permissions for accessibility where it states the app has stopped working properly.

**Comment by Squork** [comment]
> yes

OK, done

2740:

https://github.com/user-attachments/assets/f44168da-5dff-45c5-9574-152ae57b03a8

2826:


https://github.com/user-attachments/assets/3efc7203-028a-43d8-8aa6-d56ece5e9592

(in 2826 first start crashs, second start works, next starts fails)

**Comment by reconman** [comment]
Force-stopping the app should also repair it.

Fix is on the way to the play store, but already available on the Github releases page.
