### ISSUE TITLE
[NA] Lotto mode Reset Prize when out of lotto currency

### ISSUE THREAD

**Issue by gogito** [Fate-Grand-Automata/FGA#563]
So it's currently the Christmas Rerun for NA and I notice that when I run the Lotto script to open Lotto box, whenever it runs out of lotto currency and can't open box anymore, it choose reset prize and move to the next box.

I don't think this is intended nor did it happen on previous lotto.
I'm using a Pixel 3, Android 11

**Comment by MathewSachin** [comment]
This is intended in the sense that as of now we can't detect difference between running out of lotto currencies and finishing a box.
This is only a problem in the first 10 boxes where you can reset early, which is why you might not have notified before.

Mentioned here: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Lottery
> WARNING: Better avoid using the Lottery script on Boxes 1-10. If you don't have enough tickets, it can reset the box as soon as you receive the Grand Prize.

**Comment by gogito** [comment]
> 
> 
> This is intended in the sense that as of now we can't detect difference between running out of lotto currencies and finishing a box.
> This is only a problem in the first 10 boxes where you can reset early, which is why you might not have noticed before.
> 
> Mentioned here: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Lottery
> 
> > WARNING: Better avoid using the Lottery script on Boxes 1-10. If you don't have enough tickets, it can reset the box as soon as you receive the Grand Prize.

Ah I see.
I have a suggestion. How about we check the item left number to check whether we're out of lotto currency or done opening the current box?
For example: If we see 0/300 that means the box is clear, if not then the box is not clear and we jut simply ran out of lotto currency.
It's a minor thing and the current implementation is great but it's just a suggestion for more polish.
Cheers!

**Comment by MathewSachin** [comment]
Already thought of that, but since the app doesn't have text recognition we'll have to match the image of ZERO.
But, like with the Gift Box script, the font could be different for different servers. Not sure on this, but, I think the design of that part is different depending on Christmas or Nero/GIlFest.
