### ISSUE TITLE
Script can press stop button on support select screen

### ISSUE THREAD

**Issue by SleipnirTheRapid** [Fate-Grand-Automata/FGA#578]
Before opening an issue:
- [x] I tested the latest release _(v0.22.1 and CI build 1095)_
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
If a preferred CE is set, but not a servant, the script can click the stop button in an attempt to click the CE image behind it on very rare occasions. This only happens if the pause option is enabled since the start/stop button is well out of the way otherwise.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
https://streamable.com/if4y56

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Bluestacks v4.240.0.1075]
 - Screen size: [1600x900]
 - Android Version: [Android 7.1.2]
 - RAM: [4GB]

**Comment by MathewSachin** [comment]
Hmm, it's clicking on the STOP button when trying to scroll

2 workarounds come to my mind:
1. Lower the resolution to 1280x720. The PLAY/STOP button becomes bigger on higher resolutions so that users on tablets don't have trouble clicking on them.
2. Move the buttons to somewhere else. Bottom-center of the screen should be fine.

**Comment by SleipnirTheRapid** [comment]
I really doubt scrolling is the problem, because by "on very rare occasions" I mean that I've spent over a week's worth of natural AP farming bones at X-G with these settings without it happening once. I've only ever seen it occur twice, and both times the Teatime was in the bottom left of the screen with no other copy visible which is why that is my theory.

It took a few tries due to inconsistent scrolling distance, but I managed to capture a scroll before it clicked the stop button. This was recorded after changing to 1280x720 resolution, which did slightly shrink the stop button, but enlarged the pause button for some reason. Both of the videos are on the CI build by the way (the one that was the latest one a few hours ago).
https://streamable.com/81ymks

**Comment by MathewSachin** [comment]
Ah right, I misunderstood the issue. So, it's trying to click on the CE but that click is received by the STOP button.
I checked the code and doesn't seem like the regions are wrong. It's clicking where the CE use detected, so that should be a bit above the STOP button. But, that event is still received by the STOP button.
I doubt if this could be handled by the code. I think moving the buttons to somewhere else on the screen is the only thing you can try.

The size is the PLAY and PAUSE buttons varies depending on the physical size of the device which isn't apparent in emulators.

**Comment by jochuan** [comment]
> Sorry for bumping this issue but after i changed my screen size the app doesn't scroll down to look for skadi anymore and instead it updates the support screen and wait for a skadi to appear, but this can take a long time and sometimes it choses different servants.
Does someone knows a solution for this ?

**Comment by jochuan** [comment]
I think that i will have to wait for this bug to be fixed or use a older version then. Thanks anyway.

**Comment by MathewSachin** [comment]
The new PLAY button's size is consistent across resolutions and also the PAUSE button only shows up when needed. So, I think this problem won't happen now.
