### ISSUE TITLE
Announcement: I've Unpublished FGA from Google Play

### ISSUE THREAD

**Issue by MathewSachin** [Fate-Grand-Automata/FGA#616]
As FGA is right now, it doesn't work properly for JP after the fullscreen update (#571) on most devices unless they're 16:9. And updating FGA to support all different resolution of phones is no measly task.

I can't put up any updates now on PlayStore until JP support is fixed and people are already complaining a lot on that, so I decided to Unpublish from Play for the time being. Existing users can still download and use the app, but new users won't be able to download from Play anymore.

New users can get the Canary releases (similar to a Beta) here on GitHub: https://github.com/MathewSachin/Fate-Grand-Automata/releases/tag/canary.
But, keep in mind there are no update notifications provided nor do I expect to, since the app now doesn't rely on Internet permission, because many FGO communities were shitting on the app for using INTERNET permission and accusing it of stealing FGO accounts, obviously without any proofs or the ability to comprehend the source code.

**Comment by potchy** [comment]
Please take your time on this. It's not an easy problem. People did just fine before learning of the app and I'm sure they can use the workarounds available if they need it that much

**Comment by MakuSensei** [comment]
you do an excellent job. this application is really excellent. and I understand the problems that the jp version has caused. Take all the time you need to fix all those problems. I've ignored toxic communities that don't contribute anything. 
Greetings from Argentina.

**Comment by TheRealPlagiariser** [comment]
After coming back to check this project after a long pause on fgo,, I'm dumbfounded people think this could steal user information, when the source code is public for everyone to see.

Actually with the previous system which was dependent on Ankulua, this was more of a threat since Ankulua indeed could potentially be running some scripts behind the scenes without the user's knowledge. I'm really thankful for the devoted work towards this once small project started by a group of people, which is now fully independent and continuously worked upon.

Keep up the good work and as MakuSensei said above, ignore the toxicity!

**Comment by Djinnistorm** [comment]
Hey, quick question because I'm android illiterate. I have the app already on Bluestacks. What is the proper way to go about updating it for the time being? 
Oh, and thank you for this wonderful tool. I've ended up with some hand pain from PC overuse, so this has been really helpful for reducing stress on that hand. Good luck on your JP fixes!

**Comment by reconman** [comment]
@Djinnistorm I had the same problem and bought a vertical mouse similar to this one: https://www.amazon.com/Anker-Wireless-Vertical-Ergonomic-Optical/dp/B00BIFNTMC/

**Comment by sdarkpaladin** [comment]
> But, keep in mind there are no update notifications provided nor do I expect to, since the app now doesn't rely on Internet permission, because many FGO communities were shitting on the app for using INTERNET permission and accusing it of stealing FGO accounts, obviously without any proofs or the ability to comprehend the source code.

Typical non-IT literate people who always want IT and Automation to solve their problem but accuse IT of going out of the way to get them...

**Comment by achavezz** [comment]
Been trying to use the app, but getting this error "Script Exited: Couldn't detect Script type". I downloaded the apk like normal and booted it up fine and opened fgo to run it.

**Comment by reconman** [comment]
@achavezz This is not the right place to ask that. You should have opened a new issue of type question.

But anyways, have you watched my (outdated) youtube video? It should at least help you get started.
