### ISSUE TITLE
Face card stagger

### ISSUE THREAD

**Issue by Mashmallow-0** [Fate-Grand-Automata/FGA#629]
Add a feature to repeat advantage face cards while avoiding brave chains.
For example Lartoria Eresh Waver comp for Christmas 2020, card order should be Lartoria Eresh Lartoria or Eresh Lartoria Eresh. As of right now, FGA seems to go straight to Waver's Buster card after the 2nd card

**Comment by LouizFC** [comment]
@MathewSachin I would like to help implement this feature, but I am not familiar with the code base. When you have some time, could you point out the relevant classes that I should be looking for?

I was thinking about creating a way to recognize different servant face cards (similarly how we can register custom CEs).

That would also allow some use cases like prioritizing NP Gain for a specific servant, and so on

**Comment by MathewSachin** [comment]
@LouizFC  Per-servant priority is not much difficult to code, but, the UI would get very messed up with it.
See #137 which asked for selecting specific servant's cards, for my reasoning.
Brave chains feature was what I came up with as a compromise and implemented in #212. The files changed in that pull-request are the ones most relevant to you, if you still want to experiment.

---

Now, regarding this issue, Avoid brave chains does have the problem of only looking left to right on the cards so in some cases what it picks will not be the most optimal, but, I've found it satisfactory for all my use cases till now. I mean, if we're face-carding anyways, taking another turn is no big deal.

Take an example of getting the following cards (B, A, Q are Buster, Arts, Quick respectively) and assuming the default card priority with Avoid brave chains:
`Lartoria (B) Eresh (B) Eresh (B) Waver (A) Waver(B)`

You would expect it to pick `Eresh (B) Lartoria (B) Eresh (B)`.
But, since it only looks left to right as of now, it picks `Lartoria (B) Eresh (B) Waver (B)`.
Since `Lartoria (B)` and `Eresh (B)` have the same priority, it picks the first one from the left, which is `Lartoria (B)`. It then picks `Eresh (B)`. Now, it can't pick another `Eresh (B)` because `Avoid brave chains` ensures that the consecutive cards are of different servants (unless an NP is included). So, it chooses `Waver (B)` which is the card with the next highest priority and also of a different servant.
This is the case this issue is asking an improvement over.

But, it's not really simple to fix it while keeping the existing card priority mechanism.
Like, if instead, the cards were `Lartoria (B) Eresh (A) Eresh (Q) Waver (A) Waver (B)`. There's no choice but to pick `Lartoria (B)` first since it is `WB` which is the highest priority in the default case we're assuming.

**Comment by LouizFC** [comment]
> Take an example of getting the following cards (B, A, Q are Buster, Arts, Quick respectively) and assuming the default card priority with Avoid brave chains:
> 
>  Lartoria (B) Eresh (B) Eresh (B) Waver (A) Waver(B)
>  
>  You would expect it to pick Eresh (B) Lartoria (B) Eresh (B).
>  But, since it only looks left to right as of now, it picks Lartoria (B) Eresh (B) Waver (B).

I haven't read the code yet, so assuming what you just said, the problem is the card order?

If the problem is the card order, I think that pre-processing duplicate cards should be enough.

---

Lets assume the way you are current weighing is the following (let me know if it is correct):
- the card type from 1 to 9 based on the priority configured
- sorting them in crescent order, and picking the first 3
- "Avoid Brave Chains" drops **consecutive** cards.
- the following card priority (WB(1), WA(2), WQ(3), B(4), A(5), Q(6), RB(7), RA(8), RQ(9))
So, in the example, the card weight would be:
```
|   WB (1)   |   WB(1)   |   WB(x)*  |    A(5)   |   B(4)   |
Lartoria (B) | Eresh (B) | Eresh (B) | Waver (A) | Waver(B) |
* the "x" means the card is out of the sorting
```
The resulting order would be:
```
Lartoria (B) | Eresh (B) | Waver (B)
```
To have `Eresh (B) Lartoria (B) Eresh (B)`, we could add a "sorting step" to before card priority is calculated. This sorting step would group the cards by type and servant, then iterate the over the "grouped" cards and redistribute then like so:
```
Input: Lartoria (B) | Eresh (B) | Eresh (B) | Waver (A) | Waver (B)

Grouping: Lartoria (B) (1) | Eresh (B) (2) | Waver (A) (1) | Waver (B) (1)
// we sort so the cards with most appearances goes first
Sorting: Eresh (B) (2) | Lartoria (B) (1) | Waver (A) (1) | Waver (B) (1) 

First iteration:  Eresh (B) | Lartoria (B) | Waver (A) | Waver (B)
Second iteration: Eresh (B) 

Pre-processed Order: Eresh (B) | Lartoria (B) | Waver (A) | Waver (B) | Eresh (B)
Output (after calculating priority): Eresh (B) Lartoria (B) Eresh (B)
```
Then feed this card order to the priority calculator.
Another example, with "double, double cards" would be:
```
Input: Lartoria (B) | Lartoria (B) | Waver(B) | Eresh (B) | Eresh (B)

Processing: Lartoria (B) (2) | Waver (B) (1) |  Eresh (B) (2)
Sorting: Lartoria (B) (2) | Eresh (B) (2) | Waver (B) (1)
First Iteration: Lartoria (B) | Eresh (B) | Waver (B)
Second Iteration: Lartoria (B) | Eresh (B)

Output: Lartoria (B) | Eresh (B) | Waver(B) | Lartoria (B) |  | Eresh (B)
Result: Lartoria (B) | Eresh (B) | Lartoria (B)
```

**Comment by MathewSachin** [comment]
@LouizFC I decided to go with a simpler approach

- Step 1: Sort cards by user-specified priority
- Step 2: Pick top 3 priority cards and group by servant
- Step 3: If number of groups:
  - 3: fallback to Normal card selection
  - 2: Ideal case: Sort descending by group size and stagger. `g[0][0], g[1][0], g[0][1]`
  - 1: Pick the highest priority card belonging to another servant. If none, fallback to normal card selection. If found, remove least priority card from the only existing group and treat the newly picked card as another group and follow the same procedure for 2 groups.

I'll make this available in `Avoid Brave chains` with `Rearrange cards` so that people can keep the existing behaviour of `Avoid Brave chains` if they want to.
