### ISSUE TITLE
FGA accidentally select support instead of refreshing

### ISSUE THREAD

**Issue by metapone** [Fate-Grand-Automata/FGA#666]
Before opening an issue:
- [X] I tested the latest release
- [X] I looked at other issues (even the closed ones)
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] I'll fill this template properly

I'm setting FGA to search for a pretty rare CE so it usually has to refresh quite a number of times. The quest's cost is really low too so FGA must run for 1h+ normally. I have noticed a few times instead of selecting the "Update list" button it accidentally select a support, then process to hang at the first turn of combat.

I will try to upload a recording later; the first recording's quite large at 3.3GB but when I tried to copy it to my computer it apparently got corrupted and couldn't be played.

**Video:**
https://youtu.be/h-LLBTrla68

**FGA version:** Canary 1274

**Device Info:**
 - Device model: Xiaomi Redmi 5 Plus
 - Screen size: 1080x2160
 - Android Version: Android 8.1.0
 - RAM: 4GB

**Comment by metapone** [comment]
Let it ran for half an hour tonight and everything's fine; I'm guessing what happened is that FGO had been left running for so long that it started being unresponsive enough for FGA to misclick. Closing this issue for now.

**Comment by the3dsandwich** [comment]
Did you check if it clicked on the Fallback Option?

FGA is configured so that after a number of refreshes (can be changed in more settings), it automatically falls back to the fallback option, which can be Manual or First.

Check if that's the case and if so, you might want to make the number of refreshes larger, since like you said the target ce is rare.

**Comment by metapone** [comment]
@the3dsandwich 
I set it to Manual so that's definitely not it, and have seen FGA changed to manual support selection mode a few times before so I know the setting's fine.

**Comment by metapone** [comment]
Manage to snag a video again so I'm reopening this.

**Comment by MathewSachin** [comment]
Look closely at the red rectangle over the servant and CE location. It shifts down the moment you received a notification.
FGA's view of the screen becomes smaller if the Status bar shows up, which does for you when you're receiving a notification. It doesn't show on my phone though. So, instead of the click happening on Refresh button it happens slightly below it.

I think the only way around for you would be setting DND.

**Comment by metapone** [comment]
That might have been me pulling the Notification Shade down manually to check the time :/ Can't remember if it was indeed the case tho. I'll try to be mindful of that and see if the problem still happens. Closing this again.
