### ISSUE TITLE
Overlay Counter for repetitions 

### ISSUE THREAD

**Issue by Miepmeister** [Fate-Grand-Automata/FGA#706]
Basically as the title says, I made a short search on the matter and didn't find something to that regard in the issues though I might also be too stupid to use the search function for the issues lol...
anyways, idea is a bit more on the QoL side of things and came to mind while speedrunning the current event. the gist of it would be to add sort of a counter for how many repetitions of a script you wanna do if you have a certain number in mind if it's not about farming (I imagine something like a small window or something when you hit the script you want? or a second column/row for setting the number of runs next to the list of scripts?)
this would probably make the repetitions option in the refill settings redundant and ultimately makes this core of the idea a relocation of said setting..

PS: canary is a beta version as far as I understand, are there certain differences?

PSS: the app got accused of account stealing? tf I facepalmed through to the wall behind me..

PSSS: ffs why did I write so much??? sorry for the wall of text...

**Comment by reconman** [comment]
Canary is the latest stable build intended for everyone.

The feature you're requesting is already done in the "Jetpack Compose" builds, which completely change the UI layout and are currently still in the middle of development.

You can try it out here, but there might be some added bugs: https://github.com/Fate-Grand-Automata/FGA/suites/2510158249/artifacts/54288316

Also, since you can't downgrade apps to older versions on Android, you should back up your data (export your Battle Configs) before updating the app.

If you notice any bug in the Jetpack Compose version, please report it at https://github.com/Fate-Grand-Automata/FGA/pull/675.
