### ISSUE TITLE
A way to not select Arash's command cards?

### ISSUE THREAD

**Issue by narukaze132** [Fate-Grand-Automata/FGA#711]
Before opening an issue:
- [X] No one has asked for this feature before in other issues (even the closed ones)

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

I've set up a script which uses Arash on the first wave, but generally there are still a few enemies left after his NP goes off. The other party members can wrap things up by themselves on that turn, but sometimes the script selects Arash's cards even after his NP, when he obviously can't attack. At that point, the whole script breaks down. (Well, mine doesn't, but if the setup depended on 3-turn buffs being used on the first wave and persisting until the third, it probably would.)

Could something be added so the script doesn't select command cards for a given Servant after their NP card, unless there just aren't enough command cards for the other Servants? I'm pretty sure it's _possible_, given what I know about how the app works, but I don't know Android programming.

**Comment by reconman** [comment]
Setting the card priority to `Avoid brave chains` should at least help partially.

**Comment by narukaze132** [comment]
I already have it set to avoid Brave chains; it still happens.

For the record, I actually have an idea on how this feature could be implemented, I just don't know how to code it. Basically, you could have the user use a script to take pictures of the command cards on the Servant's profile page (similar to the Support Image Maker), then let them set the card priority to put those cards at the very bottom.

**Comment by MathewSachin** [comment]
> For the record, I actually have an idea on how this feature could be implemented, I just don't know how to code it. Basically, you could have the user use a script to take pictures of the command cards on the Servant's profile page (similar to the Support Image Maker), then let them set the card priority to put those cards at the very bottom.

That's not needed actually. The Brave chains and Avoid Brave chains features are already matching NP cards with face-cards without needing you to manually provide images.

This feature could be added by changing `Brave Chains` to something like `Face-card matching` (I can't think of a good name) which would have options for:
- Brave chains with NP
- Avoid Brave chains
- Avoid matching NP (**Your use case**)
- Avoid support
- Prefer support
- None

The app is undergoing some UI changes right now. So, this feature would need to be delayed since it needs changes to both UI and functionality.

**Comment by reconman** [comment]
But thinking of the feature, the same thing will happen to Chen Gong amd then you don't want to use the sacrificed Servant's cards in the same turn.

For that situation, I have no idea on how to solve it.

**Comment by MathewSachin** [comment]
#730 is now available, closing ...
