### ISSUE TITLE
Doesn't work on Poco X3 Pro (20:9)

### ISSUE THREAD

**Issue by GanganHJ** [Fate-Grand-Automata/FGA#712]
Before opening an issue:
- [✓ ] I tested the latest release
- [ ✓] I looked at other issues (even the closed ones)
- [✓ ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ ✓] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
The Auto detect isn't placed properly on screen and sometimes got error messages "Width must be positive". If the "Ignore notch is turned off it can run but if the battle already started and when it goes back to support selection screen the error "Width must be positive" came up.

**Screenshots**
Already provide video

**Video**
https://youtu.be/w45Gu7wfr-4

**Device Info (please fill at-least 'Device model'):**
 - Device model: Poco X3 Pro
 - Screen size: 1080x2400 with screen ratio of 20:9
 - Android Version: Android 11
 - RAM: 8 GB

**Comment by MathewSachin** [comment]
For your case, you should keep `Ignore notch calculation` turned OFF.

But, still, it isn't detecting that the support screen has loaded even then. I'm not sure why though.

![image](https://user-images.githubusercontent.com/10654537/118011100-4677de00-b36d-11eb-8e70-07029c9991c0.png)

Since you're using another screen recorder instead of the in-built one, I'd recommend trying to restart your phone once and try without that. I'm not sure if Poco is Xiaomi, but, if it is, you'll also have to do some steps to counter Xiaomi's battery optimizations. You can find more about it in the Troubleshooting Guide.

**Comment by GanganHJ** [comment]
Tried disabling battery optimization still didn't work. I can send you the video recorded with the built in one but it ended less than a second. I tried using a previous version 0.22.1 and it works but kept getting an error when there's no selected support on support list with a message "Width must be positive"

**Comment by MathewSachin** [comment]
v0.22.1 is really old and it's not working for you anyways.
I'm pretty sure at this point that it is Xiaomi battery optimisation along with using another recorder alongside FGA.
There's not much we can do from our side if battery optimization steps followed by force closing the app or restarting the phone doesn't work.
