### ISSUE TITLE
Start button

### ISSUE THREAD

**Issue by Ralph2610** [Fate-Grand-Automata/FGA#758]
Before opening an issue:
- [X ] I tested the latest release
- [ X] I looked at other issues (even the closed ones)
- [ X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ X] I'll fill this template properly

**Describe the bug**
When i give all the permission the app says "to start the script enter fgo" but when im in there's no play button, tried everything but still no button when i enter fgo

**Device Info (please fill at-least 'Device model'):**
 - Device model: Oppo a91
 - Screen size: 1080x2040
 - Android Version: 11
 - RAM: 8

**Comment by MathewSachin** [comment]
I myself have had this problem before on my Realme (subbrand of Oppo) phone.
It's similar to the Accessibility problem which happens due to the app process being killed when AccessibilityService is still enabled.

Unfortunately, there's no real solution from our end. You can try playing with your device's battery optimisation settings, force stop the app, restart your phone, etc.
The way I counter this problem without changing any battery optimization settings is to turn OFF the Accessibility service after every use and only turn it back ON when I want to use the app. Realme has an option to toggle AccessibilityService using gestures, so I think Oppo might have that too, which makes it very convenient to turn it OFF/ON on demand.

**Comment by Ralph2610** [comment]
Tried what you did but the play button still doesnt appear reeeeee

**Comment by the3dsandwich** [comment]
![Screenshot_1625226156](https://user-images.githubusercontent.com/32169552/124269612-acaeff00-db6d-11eb-9b16-5c31f10e2f34.png)

As a very sided side note, if your accessibility service shows "not working, tap for info", try turning it off and on again to enable it. When it shows that it's not working, it will not work.

See if your settings is like that. If not then I guess Android Emulator from Android Studio is always an option...

**Comment by MathewSachin** [comment]
That won't solve it from my experience. Oppo/Realme phones stop providing configuration change (screen rotation) info sometimes, which we can't do much about.

One possibility I could think of is to have FGA in landscape orientation before clicking on Start Service.

**Comment by Ralph2610** [comment]
Yooooo solved, you Just Need to put the automatic rotatoion, then start when the screen Is horizzontal
