### ISSUE TITLE
Select face cards based on crit stars or deprioritize face cards from support unit

### ISSUE THREAD

**Issue by mackoz** [Fate-Grand-Automata/FGA#761]
Before opening an issue:
- [x] No one has asked for this feature before in other issues (even the closed ones)

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

For the JP lotto this year, the 90+ node has many comps which involve critting down the first wave (it's a 1-1-3 node). I was wondering if it'll be possible to select face cards based on crit stars on top of the existing priority. Example: BAQ card priority, 1 buster in hand and 3 arts cards with 10, 30, 50% crit chances (from left to right). Right now it'll select the buster and 10 and 30% crit chance art cards, but I'd rather have it choose the 50%.

Another way I feel this issue can be fixed is by prioritizing damage dealer face cards over support face cards or deprioritizng the support face cards. Ex: Check if any face cards belong to Castoria, Merlin, or Skadi and only choose them if there's no other cards to choose.

https://www.youtube.com/watch?v=zq4LRr5FhNw has some comps showing the first wave being cleared by critting.

Thanks for all the hard work on this project!

**Comment by the3dsandwich** [comment]
From my understanding we're working on detecting individual servant's cards, but I don't think the update will come as soon as this event. So, we won't be having the option to prioritize a servant's cards yet. See #730 and related issue #711

For crit stars, the problem I can think of is that, since FGA does not recognize text but only recognize images (of the numbers), we need to have a good enough matching of the crit star texts, from null (0%) to 100%, which is at least 10 images to check. On top of that, the text for crit stars is unfortunately over the background, which means image matching may be difficult.

There might be some creative or cool ways that can solve these problems though, if you have any ideas then definitely let us know (where/how to match images, what images to match, etc.)!

**Comment by MathewSachin** [comment]
@the3dsandwich has already explained why crit detection cannot be done as of now.
I'll try to explain why it is a bit unrealistic.

> Example: BAQ card priority, 1 buster in hand and 3 arts cards with 10, 30, 50% crit chances (from left to right). Right now it'll select the buster and 10 and 30% crit chance art cards, but I'd rather have it choose the 50%.

Consider this example instead: BAQ priority, you have to pick between B (10%) and A (100%). The script would still have to pick B since B > A. But, you might want to pick A anyways.
Stuff like this is easy to program but hard to configure with a UI.

> https://www.youtube.com/watch?v=zq4LRr5FhNw has some comps showing the first wave being cleared by critting.

I only looked at the first comp, but, it seems that if you don't crit down the enemy in 1T, all your buffs would go to waste and the run would get butchered. I don't think this type of comp is worth the risk when using scripts that can't adapt to unexpected cases like a human can.

> Check if any face cards belong to Castoria, Merlin, or Skadi and only choose them if there's no other cards to choose.

There are other supports too. And each support has 3+ designs for face-cards which means a lot of images to hard-code in the app, so no. #730 is what we'll be going for.

**Comment by mackoz** [comment]
Got it, thanks for the crit stars explanation. I was thinking of adding a button in the UI to select which servants are the support servants so that those cards can be excluded but #730 is fine too whichever is easier to implement on your end. Thanks!
