### ISSUE TITLE
Toast notifications for accessibility won't stop

### ISSUE THREAD

**Issue by chairmanxyz** [Fate-Grand-Automata/FGA#770]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
Hey there, first off thanks so much for continuing to update the app. This new update has a lot of great stuff I'm already making use of.

Small issue on my end though is after updating, my phone's toast notifications for FGA accessibility keeps turning on and off whenever I lock and unlock my phone. Even after closing FGA completely those notifications keep going off. Only way I can get them to stop is by completely disabling FGA in my phone's accessibility settings and then turning it back on again when I want to use the app. I didn't have this issue with the previous release so I'm guessing it's a new thing that's cropped up.

 - Device model: Samsung S9+
 - Screen size: 
 - Android Version: 10
 - RAM:

**Comment by reconman** [comment]
Can you please check if anything here helps?

https://dontkillmyapp.com/samsung

It looks like Samsung disables Accessibility in general on locks.

Maybe there's a setting for that behavior somewhere in the system settings. We don't have a Samsung device so we can't check.

**Comment by MathewSachin** [comment]
> Small issue on my end though is after updating, my phone's toast notifications for FGA accessibility keeps turning on and off whenever I lock and unlock my phone.

This toast notification was added because many phones have Accessibility issues, so as to know when the Accessibility Service is being killed by the system.

> Only way I can get them to stop is by completely disabling FGA in my phone's accessibility settings and then turning it back on again when I want to use the app.

Actually, this is how Accessibility Services should be used when an application with a UI is present in the same APK. Otherwise, on many phones, Accessibility Service malfunctions if the app is killed while Accessibility Service is enabled in Settings.

> I didn't have this issue with the previous release so I'm guessing it's a new thing that's cropped up.

The app isn't malfunctioning. It is in a way letting you know that your device keeps killing it.
You could see dontkillmyapp.com, but, I would recommend that it is better to turn OFF AccessibilityService after use.

**Comment by chairmanxyz** [comment]
Yeah there's nothing in dontkillmyapp I haven't seen before. Like I said I have no issues with the functionality of FGA or accessibility permissions. The app runs all night if I want it too. Just the toast notifications are annoying and it's a bit tedious to disable FGA in accessibility and re-enable it each time.
