### ISSUE TITLE
Problem with mlb ce (Keleidoscope)

### ISSUE THREAD

**Issue by Dimastico** [Fate-Grand-Automata/FGA#776]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

I have this problem: even if I check the option to use only mlb ce, the app in game still selects the ce not mlb. I have this problem with the kaleidoscope but i have not tried with other ce.

**Device Info**
 - Device model: [Samsung A40]
 - Screen size: [1080 x 2340 pixel]
 - Android Version: [Android 11]
 - RAM: [4 GB]

**Comment by potchy** [comment]
Try going to Advanced > Fine tune and increase the value in MLB Similiraty.

![Screenshot_20210712-132448](https://user-images.githubusercontent.com/4316326/125323732-80d20d00-e315-11eb-90b9-5e0e5ebc03fc.png)

**Comment by Dimastico** [comment]
> Try going to Advanced > Fine tune and increase the value in MLB Similiraty.
> 


oh thanks i'll try

**Comment by MathewSachin** [comment]
Maybe try creating a custom Kaleidoscope image with [Support Image Maker](https://github.com/Fate-Grand-Automata/FGA/wiki/Support-Image-Maker#how-to-use-support-image-maker) like they did [here](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/2832).

Also, revert the MLB similarity value to default since increasing didn't work.
