### ISSUE TITLE
Battle script not working on FGO JP 

### ISSUE THREAD

**Issue by w-san** [Fate-Grand-Automata/FGA#779]
Updated to the new version unsure why it's not recognising the inpts again. have fullscreen mode on and everything.

**Comment by w-san** [comment]
i turned on debug mode and check it seems to not recognise battle icons or  positions again.

**Comment by MathewSachin** [comment]
Better open another issue with the `bug` template with proper details. Showing is better than telling.

**Comment by w-san** [comment]
[https://imgur.com/a/8w7T3gI](url)

**Comment by MathewSachin** [comment]
I think it's because the text that shows TOTAL critical stars is now partially overlapping the attack button.
Have to check if it's the case on other devices too.

OLD | NEW
-----|-------
<img src="https://user-images.githubusercontent.com/10654537/125615426-7aecf8d6-876d-4368-8dfc-231a7defa407.png" width="200"> | !<img src="https://user-images.githubusercontent.com/10654537/125615451-21aff178-bf5a-4c10-82c4-3173f274f692.png" width="200">

Does stuff other than Battle work? Like support selection, FP summon, etc.

**Comment by solmax958** [comment]
have the same issues on my redmi note 10, it work on support selection and stop after battle start .

**Comment by redooo98** [comment]
this is still not working for JP after installing the latest update, any help?

**Comment by w-san** [comment]
> 
> 
> this is still not working for JP after installing the latest update, any help?

i can try a bit
