### ISSUE TITLE
How to get the region location?

### ISSUE THREAD

**Issue by bkdo7bgx** [Fate-Grand-Automata/FGA#811]
Before opening an issue:
- [✓] My question isn't answered in any other issues (even the closed ones)
- [✓] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

FGA does not work properly on my device. I am trying to modify some region location, but the value I get through the pointer location in the android development options is incorrect. I have no development experience, and some region locations are confusing to me

e.g.
https://github.com/Fate-Grand-Automata/FGA/blob/a3b925a7be2856497026526afe527350f87f86ee/scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Game.kt#L354-L356

**Comment by MathewSachin** [comment]
> The X-Y Problem, as it is sometimes called, occurs when a person tries to solve a problem on their own, pursues a method that seems like a promising approach, gets stuck, and then asks for help with their chosen method (instead of asking for help with the original problem).

**Comment by bkdo7bgx** [comment]
> > The X-Y Problem, as it is sometimes called, occurs when a person tries to solve a problem on their own, pursues a method that seems like a promising approach, gets stuck, and then asks for help with their chosen method (instead of asking for help with the original problem).

Well, I admit that this question is stupid, I just want to know the meaning of these hardcode location, I will understand them by read the code

**Comment by sdarkpaladin** [comment]
I think what MathewSachin is saying is that instead of asking whatever you are asking right now, why don't you explain what you are trying to solve? That would probably help you more than telling you technical details that you might or might not know and might or might not solve your problem in the first place.

Especially considering you "have no development experience".

**Comment by reconman** [comment]
A basic explanation of `Region(-780, 860, 180, 100).xFromCenter()` is:

Assume a 1440p screenshot with X=0 and Y=0 in the top left. If the screen is 16:9, the bottom right would be X=2560, Y=1440.

The first 2 values in the Region are the X and Y location of the top left corner coordinates of a rectangle. So that would be X=-780 and Y=860.

The `xFromCenter()` adds half of the screen width to X. Half the screen width is 1280, so the top left corner of the rectangle is at X=500, Y=860.

180 and 100 are the width and height of the rectangle.

If your device has notches, the X values are all shifted to the right on all FGO versions but JP. On NA, X=0 should be at the end of the left blue border.

If your device is 720p, all coordinate values are halfed, so the rectangle will only be 90x50 pixels big. If it's 1080p, then it's 135x75.

But as others have said, if you just show us what's going on, we can help you. We only know a handful of phones where it doesn't work. In most cases you have to change some system settings in order to make it work.
