### ISSUE TITLE
Adding AP0 Quests start button

### ISSUE THREAD

**Issue by gdays9000** [Fate-Grand-Automata/FGA#872]
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

Hello! FGA developer(s) and Sachin-san.

I have been playing this game over a year now and use it everyday. I really appreciate FGA and would not 
have made through this game without it.

I would like to suggest to add a feature that starts a quest that appears mainly on AP0 quests in FGO.

![IMG_20210911_182152](https://user-images.githubusercontent.com/87426308/132943055-b28cb7c3-b9e5-4443-b112-a61e8e0c185e.jpg)

In AP0 quests, the box appears indicating that "このクエストにはバトルがありません" and the FGA would not move forward unless the player manually press the button "クエスト開始"

I have looked through "enhancement" but could not find anyone asking for this feature.

I am pretty sure that developer(s) may have thought about it already, but this feature was not added because it is technically too difficult to realise it?

But just in case, I would like to suggest this feature.

Thank you,

And have a good day!

**Comment by MathewSachin** [comment]
We didn't add support for this since this case only happens in story and we don't intend for FGA to automate story.
Even if we had decided to support this, to detect that button, will need to add images from all 5 servers, which isn't worth it. Adding more images for every small thing isn't efficient.
