### ISSUE TITLE
Latest update adjusted some UI elements.

### ISSUE THREAD

**Issue by Stundedx** [Fate-Grand-Automata/FGA#943]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1551

### Describe the bug

New update seems to adjust some UI elements, thus making the scanning a bit off, especially in the support screen(as seen in the video provided).  Everything worked perfectly before this particular update.

### Video

https://streamable.com/7mmlpu

### Device model

VIVO Y20s

### Android version

11

### Screen size

1600 x 720

### RAM

8

**Comment by reconman** [comment]
Manager at DW: How can we prevent users from using FGA?
Developer: Let's just change the UI on every update until the FGA devs and users give up.

**Comment by reconman** [comment]
Since I lost my JP account and doing the tutorial takes so long, I would need someone to provide the following screenshots from JP to be able to work on this issue:

1. Screenshot in 1280x720
2. Screenshot in 1440x720 (wide screen)

Seems to me like the buttons are scaled differently now but it could be a video artefact. That's why I need screenshots.

**Comment by Tom3kk** [comment]
I have this issue on NA on Nox, it doesn't seem like a JP exclusive problem.

**Comment by reconman** [comment]
@Tom3kk I'll need a video in a new bug issue, it's probably unrelated.

**Comment by Tom3kk** [comment]
@reconman the video attached to this issue looks exactly the same excuse me fumbling with the accessibility 
[Video](https://youtu.be/L6X9lfVraYk)

**Comment by reconman** [comment]
@Tom3kk You didn't open a new issue, also you have Screenshots with Root disabled, that's probably why it doesn't work. Your issue is addressed at https://github.com/Fate-Grand-Automata/FGA/wiki/Running-on-Emulators#nox

If you create any more comments in this thread, I'll mark them as off-topic and ignore them.

**Comment by reconman** [comment]
Played through the tutorial:

![Screenshot_2021 12 06_23 13 17 317](https://user-images.githubusercontent.com/12360257/144931371-86c65809-b7af-4f85-9c0f-c2ea0eb7ac97.png)

![Screenshot_2021 12 06_23 16 37 297](https://user-images.githubusercontent.com/12360257/144931771-01403e45-f49b-4e48-8913-1e694b697739.png)

**Comment by reconman** [comment]
Can you check if https://github.com/Fate-Grand-Automata/FGA/suites/4572370684/artifacts/123034329 works?

**Comment by reconman** [comment]
19:9:
![Screenshot_2021 12 12_14 58 44 474](https://user-images.githubusercontent.com/12360257/145715589-8ca39a8b-9f7b-4ff9-b16e-307724989fdc.png)

20:9:
![Screenshot_2021 12 12_15 00 36 731](https://user-images.githubusercontent.com/12360257/145715596-12a6d7b2-c2da-4e1a-9eff-59a11a1d0ae1.png)

**Comment by reconman** [comment]
I thought the stretched buttons are due to different resolutions, but in Bluestacks, the buttons are never stretched like in the video above or in https://youtu.be/QWfjfA5RfW0 (Xiaomi)

Something weird is going on here...

I analyzed my Bluestacks screenshot and the change in my PR only fixes 18:9 resolutions but breaks 19:9 and 20:9. The old code works on 16:9, 19:9 and 20:9 except for the few devices who stretch the buttons in this screen.
