### ISSUE TITLE
Automation not starting

### ISSUE THREAD

**Issue by Welius13** [Fate-Grand-Automata/FGA#955]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

Automation doesn't work. The script starts but it doesn't identify any location to press. Have tried to start script in 3 different locations (video). Overworld quest, Friend list and Wave 1 of the node

### Video

[https://streamable.com/unblv5](https://streamable.com/unblv5)

### Device model

Asus ROG 5 Ultimate

### Android version

11

### Screen size

1080x2448

### RAM

18GB

**Comment by Djinnistorm** [comment]
You need to select a mission to run.

**Comment by Welius13** [comment]
Talked more with the person facing the problem (just a proxy myself) and updated the description to clarify the problem. Missions are running but the script isn't able to locate the buttons to press.
This is most likely due to uncommon screen proportions that lead to the buttons showing up in unusual locations.

**Comment by Santicx** [comment]
yea I have the same phone as you do and also have the same trouble as you. 
not sure if you could select the resolution of screen in the game setting, going back to the old screen is something I do not mind at all to be honest.

**Comment by TheKeiki** [comment]
Exact same behavor here, the app stop working after yesterday update when they implemented the fullscreen GUI on the EN server,  tried in a Galaxy S9 (1440x2960) and in a Galaxy Note 20 (1080x2400). Using the debug mode and the detection zones are all over the place I think.

![Screenshot_20211117-142520_FateGO](https://user-images.githubusercontent.com/21253128/142277138-892f9b44-8981-4e20-ac93-0bedfc184514.jpg)

**Comment by hayate1412** [comment]
Yeah. Automata doesn't work for samsung s20 fe 5g as well. Same problems which are described above.

**Comment by maanikbhandari** [comment]
Same issue on a Pixel 4 XL, screen resolution of 3040x1440

**Comment by MathewSachin** [comment]
As mentioned in the troubleshooting guide, FGA would only work if FGO covers the whole screen with no black bars. This has been the case since JP got the full-screen update.

I can't say much about ASUS phones, but I'm pretty sure all (maybe not dual screen ones) Samsung phones work fine if you make FGO a full-screen app.
For some phones like Pixel which have stock Android, FGO seems to leave black areas in gesture navigation but doesn't in 3-button layout. Switching to the later should work.

Anyways, we cannot support every resolution so you pretty much have 2 options:
1. Get FGO to fill the whole screen without any black areas.
2. Fork the code base and hardcode values for your phone's regions. Game Area Mode should make this very easy for any reasonable programmer.
    I won't add more game area modes into FGA unless it is a very special case where the values can be calculated and not hardcoded like in the case of Xperia devices.

**Comment by hayate1412** [comment]
I dont have any black area though
![Uploading Screenshot_20211118-073522_FateGO.jpg…]()
![Uploading Screenshot_20211118-073516_FateGO.jpg…]()

**Comment by reconman** [comment]
@hayate1412 You pressed Comment too soon, your images are broken.

**Comment by MathewSachin** [comment]
Seems like ASUS phones also have the option to make full-screen:

https://community.gamepress.gg/t/fate-grand-automata-discussion-and-help-thread-round-2/107040/471

**Comment by hayate1412** [comment]
Oh. My bad
My phone is samsung s20 fe 5g
![Screenshot_20211118-073522_FateGO](https://user-images.githubusercontent.com/59958509/142726969-c3938bf9-5681-485e-843e-6196fa6be531.jpg)
![Screenshot_20211118-073516_FateGO](https://user-images.githubusercontent.com/59958509/142726985-2ad395fb-4e93-4469-b542-da997763e7f0.jpg)
Let me know if the pics are still broken

**Comment by reconman** [comment]
@hayate1412 We need a video to see what's wrong, the screenshots don't show any black areas as you said.

**Comment by MathewSachin** [comment]
Since it is a different problem, let's not take this thread off topic. Opening a new issue is better.

**Comment by hayate1412** [comment]
> @hayate1412 We need a video to see what's wrong, the screenshots don't show any black areas as you said.

https://youtu.be/qgplSDrsEOY

Here is the video. Let me know if there is specific tests u want to have me do.

**Comment by StateRoute67** [comment]
So I have a Pixel 4a 5G and switched to the 3 button layout to make FGA do something again. The problem is...it does pick supports and starts quests but then it does completely random stuff when it comes to card selection and skill usage. My battle configs are the same, nothing was changed yet it makes servants buff different servants than the config says it should buff.

**Comment by shanashiina1407** [comment]
@MathewSachin  so which phone does FGA support ? I play on Nox 7( Galaxy Note 10+)  and it won't work either .

**Comment by TheKeiki** [comment]
Pretty much in every phone that supports full screen-apps, as mentioned before if your phone has black bars it won't work, almost every samsung phone has the feature to make the app full screen on the display settings, although I am not sure if that an option in emulators like nox.

**Comment by vybze** [comment]
#1347
